-- ============================================================
-- PROJETO LÓGICO DE BANCO DE DADOS - OFICINA
-- MySQL 8+
-- ============================================================

DROP DATABASE IF EXISTS oficina_dio;
CREATE DATABASE oficina_dio;
USE oficina_dio;

CREATE TABLE CLIENTE (
    idCLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    CONSTRAINT chk_cliente_cpf
        CHECK (CPF REGEXP '^[0-9]{3}\\.[0-9]{3}\\.[0-9]{3}-[0-9]{2}$')
);

CREATE TABLE VEICULO (
    idVEICULO INT AUTO_INCREMENT PRIMARY KEY,
    PLACA VARCHAR(10) NOT NULL UNIQUE,
    MODELO VARCHAR(45) NOT NULL,
    MARCA VARCHAR(45) NOT NULL,
    ANO YEAR NOT NULL,
    CLIENTE_idCLIENTE INT NOT NULL,
    CONSTRAINT fk_veiculo_cliente
        FOREIGN KEY (CLIENTE_idCLIENTE) REFERENCES CLIENTE(idCLIENTE)
        ON DELETE CASCADE
);

CREATE TABLE EQUIPE (
    idEQUIPE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_EQUIPE VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE MECANICO (
    idMECANICO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    ESPECIALIDADE VARCHAR(45) NOT NULL,
    EQUIPE_idEQUIPE INT NOT NULL,
    CONSTRAINT fk_mecanico_equipe
        FOREIGN KEY (EQUIPE_idEQUIPE) REFERENCES EQUIPE(idEQUIPE)
);

CREATE TABLE ORDEM_SERVICO (
    idORDEM_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
    DATA_EMISSAO DATE NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL DEFAULT 0,
    STATUS VARCHAR(45) NOT NULL,
    DATA_CONCLUSAO DATE,
    VEICULO_idVEICULO INT NOT NULL,
    EQUIPE_idEQUIPE INT NOT NULL,
    CONSTRAINT fk_os_veiculo
        FOREIGN KEY (VEICULO_idVEICULO) REFERENCES VEICULO(idVEICULO),
    CONSTRAINT fk_os_equipe
        FOREIGN KEY (EQUIPE_idEQUIPE) REFERENCES EQUIPE(idEQUIPE),
    CONSTRAINT chk_status_os
        CHECK (STATUS IN ('ABERTA', 'EM_ANDAMENTO', 'AGUARDANDO_PECA', 'CONCLUIDA', 'CANCELADA')),
    CONSTRAINT chk_valor_os CHECK (VALOR >= 0),
    CONSTRAINT chk_datas_os CHECK (DATA_CONCLUSAO IS NULL OR DATA_CONCLUSAO >= DATA_EMISSAO)
);

CREATE TABLE PECA (
    idPECA INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(150) NOT NULL,
    VALOR_UNITARIO DECIMAL(10,2) NOT NULL,
    CONSTRAINT chk_valor_peca CHECK (VALOR_UNITARIO >= 0)
);

CREATE TABLE SERVICO (
    idSERVICO INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(150) NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    CONSTRAINT chk_valor_servico CHECK (VALOR >= 0)
);

CREATE TABLE ORDEM_SERVICO_has_PECA (
    ORDEM_SERVICO_idORDEM_SERVICO INT NOT NULL,
    PECA_idPECA INT NOT NULL,
    QUANTIDADE INT NOT NULL DEFAULT 1,
    PRIMARY KEY (ORDEM_SERVICO_idORDEM_SERVICO, PECA_idPECA),
    CONSTRAINT fk_os_peca_os
        FOREIGN KEY (ORDEM_SERVICO_idORDEM_SERVICO) REFERENCES ORDEM_SERVICO(idORDEM_SERVICO)
        ON DELETE CASCADE,
    CONSTRAINT fk_os_peca_peca
        FOREIGN KEY (PECA_idPECA) REFERENCES PECA(idPECA),
    CONSTRAINT chk_quantidade_peca CHECK (QUANTIDADE > 0)
);

CREATE TABLE ORDEM_SERVICO_has_SERVICO (
    ORDEM_SERVICO_idORDEM_SERVICO INT NOT NULL,
    SERVICO_idSERVICO INT NOT NULL,
    PRIMARY KEY (ORDEM_SERVICO_idORDEM_SERVICO, SERVICO_idSERVICO),
    CONSTRAINT fk_os_servico_os
        FOREIGN KEY (ORDEM_SERVICO_idORDEM_SERVICO) REFERENCES ORDEM_SERVICO(idORDEM_SERVICO)
        ON DELETE CASCADE,
    CONSTRAINT fk_os_servico_servico
        FOREIGN KEY (SERVICO_idSERVICO) REFERENCES SERVICO(idSERVICO)
);
